### ISSUE TITLE
aiohttp is not implemented/supported?

### ISSUE THREAD

**Issue by dcermak** [MarcoMuellner/openapi-python-generator#6]
**Describe the bug**

It appears that that aiohttp is not supported by the openapi-python-generator, although the CLI suggests it is there: https://github.com/MarcoMuellner/openapi-python-generator/blob/65dc87cf3e9e806104cfbf9a191ce34d184a2f66/src/openapi_python_generator/common.py#L33

However, when you invoke `openapi-python-generator` with `--library aiohttp`, then you get the following exception:
```ShellSession
Traceback (most recent call last):
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/bin/openapi-python-generator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/openapi_python_generator/__main__.py", line 49, in main
    generate_data(source, output, library, env_token_name, use_orjson)
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/openapi_python_generator/generate_data.py", line 142, in generate_data
    result = generator(data, library_config_dict[library], env_token_name, use_orjson)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/openapi_python_generator/language_converters/python/generator.py", line 37, in generator
    services = generate_services(data.paths, library_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/openapi_python_generator/language_converters/python/service_generator.py", line 278, in generate_services
    async_so = generate_service_operation(op, path_name, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/openapi_python_generator/language_converters/python/service_generator.py", line 251, in generate_service_operation
    so.content = JINJA_ENV.get_template(library_config.template_name).render(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/.cache/pypoetry/virtualenvs/scm-staging-UcbLi63M-py3.11/lib/python3.11/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: aiohttp.jinja2
```

Looks like this file is missing or is aiohttp just not supported?

**Comment by MarcoMuellner** [comment]
This is indeed correct - I haven't gotten around to implementing it yet, but added it already in the CLI (this is an oversight). Would you be interested in implementing it? It should be rather straight forward with the jinja2 template files.

**Comment by dcermak** [comment]
Thank you, I can confirm that it now successfully creates an API wrapper!
