### ISSUE TITLE
Codeformatter cannot parse generated source code (black.parsing.InvalidInput)

### ISSUE THREAD

**Issue by swanitzek** [MarcoMuellner/openapi-python-generator#61]
**Describe the bug**
The formatting of the generated code fails because "black" is considering it as not parseable.

**To Reproduce**
1. Call `openapi-python-generator xyz.json output`
2. Observe console output

**Expected behavior**
The code should be completely generated and formatted.

**Stacktrace**

```
Generating data from v3.json
Error in model Association: invalid syntax (<string>, line 27)
Error in model TraceabilityItem: invalid syntax (<string>, line 22)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\_Tools\Python312\Scripts\openapi-python-generator.exe\__main__.py", line 7, in <module>
  File "C:\_Tools\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Tools\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\_Tools\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Tools\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Tools\Python312\Lib\site-packages\openapi_python_generator\__main__.py", line 49, in main
    generate_data(source, output, library, env_token_name, use_orjson)
  File "C:\_Tools\Python312\Lib\site-packages\openapi_python_generator\generate_data.py", line 149, in generate_data
    write_data(result, output)
  File "C:\_Tools\Python312\Lib\site-packages\openapi_python_generator\generate_data.py", line 101, in write_data
    write_code(models_path / f"{model.file_name}.py", model.content)
  File "C:\_Tools\Python312\Lib\site-packages\openapi_python_generator\generate_data.py", line 43, in write_code
    raise e
  File "C:\_Tools\Python312\Lib\site-packages\openapi_python_generator\generate_data.py", line 34, in write_code
    formatted_contend = black.format_file_contents(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\black\__init__.py", line 1021, in format_file_contents
  File "src\black\__init__.py", line 1172, in format_str
  File "src\black\__init__.py", line 1186, in _format_str_once
  File "src\black\parsing.py", line 89, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 27:9:     from : AbstractReference = Field(alias="from" )
```

**Comment by an23rd** [comment]
I ran into the same issue, almost one year later. Wouldn’t it be reasonable to only enable the formatting on request, or disable it with an option. I know that this was possible at some point (dug a little into the Git history). Personally, I’d anyway run yapf with some personal settings.

What do you think?

**Comment by MarcoMuellner** [comment]
Would any of you want to pose a pull request, that implements this feature as stated? (i.e. an option to disable black)

**Comment by an23rd** [comment]
How about the following?

https://github.com/an23rd/openapi-python-generator/commit/40f0e789aa5744943a187018ecd702dd47fa9a9f

I tested it on the OpenAPI spec I want to create a client for and it worked with the new argument `--formatter none`.

Should I run the command `not` too? It changes a lot of files. Mostly code formatting I guess.

**Comment by MarcoMuellner** [comment]
> Should I run the command not too? It changes a lot of files. Mostly code formatting I guess.
Not sure what you mean here, can you ellaborate?

Solution looks in general pretty good to me :) I'd prefer to use `None` instead of none as an enum option, that would be nice. 

A test would be great as well - maybe call black in the test on the generated code and expect two different results from black, depending on if None was used or black?

**Comment by MarcoMuellner** [comment]
No need for the nox command - i'll need to adapt the autoformatting of the code at some point in the future. 

Thank you :) Pose a PR whenever you are ready
