### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by bringert** [MarcoMuellner/openapi-python-generator#80]
**Describe the bug**
There seems to be an undeclared dependency on the `pyyaml` package.

**To Reproduce**
1. Run:
`pipx run openapi-python-generator`

**Expected behavior**
`openapi-python-generator` runs

**Screenshots**
```
$ pipx run openapi-python-generator
Traceback (most recent call last):
  File "/home/bjorn/.cache/pipx/74ca6dbc27a328b/bin/openapi-python-generator", line 5, in <module>
    from openapi_python_generator.__main__ import main
  File "/home/bjorn/.cache/pipx/74ca6dbc27a328b/lib/python3.12/site-packages/openapi_python_generator/__main__.py", line 8, in <module>
    from openapi_python_generator.generate_data import generate_data
  File "/home/bjorn/.cache/pipx/74ca6dbc27a328b/lib/python3.12/site-packages/openapi_python_generator/generate_data.py", line 10, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

The same thing happens when installing with `pip install` and then running `openapi-python-generator`.

**Desktop (please complete the following information):**
Python 3.12.3 on Ubuntu 24.04.1 LTS

**Comment by nklamann** [comment]
There seems to be something missing in pyproject.toml
